apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-booking-deployment
  labels:
    app: ticket-booking-app
spec:
  replicas: 2   # number of pods to run (you can scale this later)
  selector:
    matchLabels:
      app: ticket-booking-app
  template:
    metadata:
      labels:
        app: ticket-booking-app
    spec:
      containers:
        - name: ticket-booking-app
          image: swethavuggi/ticket-booking-app:latest   # full Docker Hub path
          ports:
            - containerPort: 80
          imagePullPolicy: Always
