apiVersion: v1
kind: Service
metadata:
  name: ticket-booking-service
  labels:
    app: ticket-booking-app
spec:
  type: NodePort
  selector:
    app: ticket-booking-app
  ports:
    - port: 80         # service port (inside the cluster)
      targetPort: 80   # container port (matches containerPort above)
      nodePort: 30009  # external access port on localhost
